spring.application.name=backend
spring.data.mongodb.uri = mongodb+srv://sigclc_dev:sigclcForEver123@sigclccluster.yzlqfq9.mongodb.net/
spring.data.mongodb.database = SIGCLC
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB